import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/navbar/Navbar'
import Footer from './components/footer/footer'
import ThemeProvider from '../../context/ThemeContext'
import {Provider} from './components/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: process.env.NEXT_PUBLIC_APP_NAME,
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <Provider>
          <div className=' lg:px-44 md:px-10 px-3'>
            <Navbar/>
              <div className=' min-h-screen'>
                {children}
              </div>
          </div>
          <Footer/>
          </Provider>
        </ThemeProvider> 
      </body>
    </html>
  )
}